### ISSUE TITLE
Media player entity not created

### ISSUE THREAD

**Issue by str2der** [ppanagiotis/pymusiccast#14]
I have installed the pymusiccast via Hacs. The files (and the __pycache__ folder) is located in:

/config/custom_components/musiccast_yamaha/

I have also added the following to Configuration.yaml:

media_player:
  - platform: musiccast_yamaha
    host: 192.168.1.192
    port: 5004

However - when I restart HA, it doesn't create a media player entity as I was expecting. Am I doing something wrong?

**Comment by ppanagiotis** [comment]
Is `192.168.1.192` accessible through your home assistant? 
try 
`telnet 192.168.1.192 80` from your home assistant device.

**Comment by str2der** [comment]
Hi! Thanks for reaching out!

I'm running HA on a virtual Ubuntu server that is running in Oracle VM Virtualbox on a Win10 machine.

From the Win10 machine I can open 192.168.1.192 in Chrome to access the web interface of the Musiccast unit. When trying with Telnet from the Win10 machine I get "Connection to host lost" after a while.

Don't know if the information is of any use, but in Configuration.yaml I already have the following, working as it should:

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.135
    token: A_LOT_OF_CHARACTERS
    name: Robostina

So it seems that the HA server can at least access that IP address correctly.

**Comment by str2der** [comment]
Managed to get it working!

Don't actually know what was wrong from the beginning, but I re-installed the component. Made sure all Musiccasts were not in standby and then added all the Musiccasts to configuration.yaml

**Comment by ppanagiotis** [comment]
Great! Have fun.
