### ISSUE TITLE
Rename and ignore source items

### ISSUE THREAD

**Issue by DennisWilken** [ppanagiotis/pymusiccast#17]
Is there an option to rename source elements, e.g. 'hdmi1' -> 'FireTV'? Additionally, I would like to hide single elements from the source list like 'tidal'. The yamaha package has a source_names and source_ignore option - is there something similar?

So far, I am using musiccast_yamaha only in combination with the mini media player. Therefore, a solution on the UI side would also be sufficient. However, I couldn't find one either.

Thanks for your help!

**Comment by ppanagiotis** [comment]
v0.4 now supports source rename and source ignore. thanks @KaSroka !
