### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'musiccast_yamaha'.

### ISSUE THREAD

**Issue by str2der** [ppanagiotis/pymusiccast#21]
Get this message in the log when starting up HA:

No 'version' key in the manifest file for custom integration 'musiccast_yamaha'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'musiccast_yamaha'

**Comment by str2der** [comment]
I'm very far from a developer, but editing the manifest.json file by adding the version fixed the issue for me:

{
  "domain": "musiccast_yamaha",
  "name": "MusicCast Yamaha",
  "version": "0.4",
  "documentation": "https://github.com/ppanagiotis/pymusiccast",
  "issue_tracker": "https://github.com/ppanagiotis/pymusiccast/issues",
  "manifest": "https://raw.githubusercontent.com/ppanagiotis/pymusiccast/master/custom_components/musiccast_yamaha/manifest.json",
  "requirements": ["pymusiccast==0.1.6"],
  "codeowners": ["@ppanagiotis"]
}

**Comment by ppanagiotis** [comment]
Update the version and add the version key at manifest.json. Thank you!!
