### ISSUE TITLE
pymusiccast will BREAK next month (2021.6)  No 'version' key in the manifest file

### ISSUE THREAD

**Issue by dmperl** [ppanagiotis/pymusiccast#23]
Apparently pymusiccast will BREAK next month (2021.6)
From HA log after upgrade to:  core-2021.5.5

Logger: homeassistant.loader
Source: loader.py:794
First occurred: May 25, 2021, 10:14:58 PM (1 occurrences)
Last logged: May 25, 2021, 10:14:58 PM

No 'version' key in the manifest file for custom integration 'musiccast_yamaha'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'musiccast_yamaha'

**Comment by ppanagiotis** [comment]
Have you update pymusiccast? Latest version (v0.5) has version key.

**Comment by dmperl** [comment]
Doh!

v.0.5 is now installed...   

Thanks!
